[setup_files]

[setup_files.jar1]
url = "https://repo1.maven.org/maven2/ai/rapids/cudf/21.12.2/cudf-21.12.2-cuda11.jar"
output_file = "cudf-21.12.2-cuda11.jar"

[setup_files.jar2]
url = "https://repo1.maven.org/maven2/com/nvidia/rapids-4-spark_2.12/21.12.0/rapids-4-spark_2.12-21.12.0.jar"
output_file = "rapids-4-spark_2.12-21.12.0.jar"